x-veld:
  code:
    description: "A spacy trainig setup, utilizing spacy v3's config system."
    topic:
      - "NLP"
      - "Machine learning"

    input:
      - volume: /veld/input/docbin/
        file_type: "spacy docbin"
        environment_var: in_train_docbin_file
        content:
          - "NLP gold data"
          - "ML gold data"
          - "gold data"
      - volume: /veld/input/docbin/
        file_type: "spacy docbin"
        environment_var: in_dev_docbin_file
        content:
          - "NLP gold data"
          - "ML gold data"
          - "gold data"
      - volume: /veld/input/docbin/
        file_type: "spacy docbin"
        environment_var: in_eval_docbin_file
        content: 
          - "NLP gold data"
          - "ML gold data"
          - "gold data"
      - volume: /veld/input/config/
        file_type: "cfg"
        environment_var: in_spacy_config
        content: "spacy training config"
        description: "See https://spacy.io/usage/training/#config"

    output:
      - volume: /veld/output/
        file_type: "spacy model"
        content: 
          - "NLP model"
          - "spacy model"
      - volume: /veld/output/
        file_type: "txt"
        environment_var: out_train_log_file
        description: "path to the train log file"
        content: "logs"
      - volume: /veld/output/
        file_type: "txt"
        environment_var: out_eval_log_file
        description: "path to the eval log file"
        content: "logs"

    config:
      - environment_var: model_base
        description: "spacy model to be used for downstream training."
        var_type: str

services:
  veld_train:
    build: .
    working_dir: /veld/code/
    command: /veld/code/train.sh
    volumes:
      - ./src/:/veld/code/
      - ./data/models_base_cache/:/tmp/models_base_cache/
      - ./data/docbin/:/veld/input/docbin/
      - ./data/config/:/veld/input/config/
      - ./data/model/:/veld/output/
    environment:
      in_train_docbin_file: null
      in_dev_docbin_file: null
      in_eval_docbin_file: null
      model_base: null
      out_train_log_file: null
      out_eval_log_file: null

