x-veld:
  code:
    description: "A spacy trainig setup, utilizing spacy v3's config system."
    topics:
      - "NLP"
      - "Machine learning"

    inputs:
      - volume: /veld/input/docbin/
        file_type: "spacy docbin"
        environment: in_train_docbin_file
        contents:
          - "NLP gold data"
          - "ML gold data"
          - "gold data"
      - volume: /veld/input/docbin/
        file_type: "spacy docbin"
        environment: in_dev_docbin_file
        contents:
          - "NLP gold data"
          - "ML gold data"
          - "gold data"
      - volume: /veld/input/docbin/
        file_type: "spacy docbin"
        environment: in_eval_docbin_file
        contents: 
          - "NLP gold data"
          - "ML gold data"
          - "gold data"
      - volume: /veld/input/config/
        file_type: "cfg"
        environment: in_spacy_config
        contents: "spacy training config"
        description: "See https://spacy.io/usage/training/#config"

    outputs:
      - volume: /veld/output/
        file_type: "spacy model"
        contents: 
          - "NLP model"
          - "spacy model"
      - volume: /veld/output/
        file_type: "txt"
        environment: out_train_log_file
        description: "path to the train log file"
        contents: "logs"
      - volume: /veld/output/
        file_type: "txt"
        environment: out_eval_log_file
        description: "path to the eval log file"
        contents: "logs"

    settings:
      - environment: model_base
        description: "spacy model to be used for downstream training."
        env_type: str

services:
  veld_train:
    build: .
    working_dir: /veld/code/
    command: /veld/code/train.sh
    volumes:
      - ./src/:/veld/code/
      - ./data/models_base_cache/:/tmp/models_base_cache/
      - ./data/docbin/:/veld/input/docbin/
      - ./data/config/:/veld/input/config/
      - ./data/model/:/veld/output/
    environment:
      in_train_docbin_file: null
      in_dev_docbin_file: null
      in_eval_docbin_file: null
      model_base: null
      out_train_log_file: null
      out_eval_log_file: null

